### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lifeinchords** [xuxinhang/snowpack-plugin-ejs#1]
Hi there!

Thanks for this plugin, it's awesome to use ejs in Snowpack.

I would like to use this in my project but we can't use GNU as we don't own the other parts of the codebase.
Would you consider licensing as MIT or Apache?

Much appreciated!

**Comment by xuxinhang** [comment]
Hello,

Sorry for my late reply.

This project is licensed under the LGPL, which means GNU *Lesser* GPL, instead of the "general" GNU GPL. So, feel free to use it as a development helper plugin.

	                    GNU LESSER GENERAL PUBLIC LICENSE
	                         Version 2.1, February 1999

	    5. A program that contains no derivative of any portion of the
	  Library, but is designed to work with the Library by being compiled or
	  linked with it, is called a "work that uses the Library".  Such a
	  work, in isolation, is not a derivative work of the Library, and
	  therefore falls outside the scope of this License.


Besides, that's a good idea to release this plugin under the same license of Snowpack itself. I will change it later . Thanks!

**Comment by lifeinchords** [comment]
Thank you for explaining and updating the license!
It's super useful for lightweight apps

**Comment by xuxinhang** [comment]
Thanks. Happy coding.
